server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
#      host: 127.0.0.1  # consul地址
      host: 192.168.216.129  # consul地址
      port: 8500      # consul端口 默认：8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: payment-router1 # 路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，通常配置服务名
          uri: lb://payment-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/provider/pay/gateway/info/**  #  断言，路径相匹配的进行路由
        - id: payment-router2 # 路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，通常配置服务名
          uri: lb://payment-service
          predicates:
#            - Cookie=username, hushunpeng   # 路由Cookie谓词工厂,匹配具有给定名称且其值与正则表达式匹配的 cookie
#            - Header=X-Request-Id, \d+      # 路由Header谓词工厂，X-Request-Id其值与\d+正则表达式匹配
#            - Host=**.baidu.com              # 路由Host谓词工厂, Ant 样式的模式，以.作为分隔符,此谓词匹配与Host模式匹配的标头,如果请求的Host标头值为www.somehost.org或beta.somehost.org或 ，www.anotherhost.org则此路由匹配
            - Path=/provider/pay/gateway/** #  路径路由谓词, 此谓词将 URI 模板变量（例如segment，在上例中定义）提取为名称和值的映射
#            - Query=username, \d+           # 路由Query谓词工厂,如果请求包含一个red查询参数，并且该参数的值与gree.正则表达式匹配，则前面的路由匹配，因此green和greet将匹配 eg:username=123
            - After=2024-05-18T19:00:00.666989600+08:00[Asia/Shanghai] # 路由After谓词工厂,匹配指定日期时间之后发生的请求
#            - Before=2024-05-14T16:20:00.666989600+08:00[Asia/Shanghai] # 路由Before谓词工厂，匹配在指定的日期之前发生的请求
#            - Between=2024-05-14T16:00:00.666989600+08:00[Asia/Shanghai], 2024-05-14T17:00:00.666989600+08:00[Asia/Shanghai] # 路由Between谓词工厂,匹配之前datetime1和之后发生的请求datetime2
#            - RemoteAddr=192.168.216.1/24     # 路由RemoteAddr谓词工厂,CIDR 表示法 eg:192.168.0.1/16（其中192.168.0.1是 IP 地址，16是子网掩码）
#            - Method=POST                 # 路由Method谓词工厂, 要匹配的 HTTP 方法
            - My=vip                 # 自定义路由谓词工厂, 小bug: 配置注解不生效？
#            - name: My               # 自定义路由谓词工厂, 完整自定义配置路由规则
#              args:
#                userType: vip