server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
#      host: 127.0.0.1  # consul地址
      host: 192.168.241.130  # consul地址
      port: 8500      # consul端口 默认：8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: payment-router1 # 路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，通常配置服务名
          uri: lb://payment-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/provider/pay/gateway/info/**  #  断言，路径相匹配的进行路由
        - id: payment-router2 # 路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，通常配置服务名
          uri: lb://payment-service
          predicates:
            - Cookie=username, hushunpeng   # 路由Cookie谓词工厂,匹配具有给定名称且其值与正则表达式匹配的 cookie
            - Path=/provider/pay/gateway/selectOne/** #  断言，路径相匹配的进行路由
            - After=2024-05-18T19:00:00.666989600+08:00[Asia/Shanghai] # 路由After谓词工厂,匹配指定日期时间之后发生的请求
#            - Before=2024-05-14T16:20:00.666989600+08:00[Asia/Shanghai] # 路由Before谓词工厂，匹配在指定的日期之前发生的请求
#            - Between=2024-05-14T16:00:00.666989600+08:00[Asia/Shanghai], 2024-05-14T17:00:00.666989600+08:00[Asia/Shanghai] # 路由Between谓词工厂,匹配之前datetime1和之后发生的请求datetime2
