server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: 127.0.0.1  # consul地址
#      host: 192.168.241.128  # consul地址
      port: 8500      # consul端口 默认：8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: payment-router1 # 路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，通常配置服务名
          uri: lb://payment-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/provider/pay/gateway/info/**  #  断言，路径相匹配的进行路由
        - id: payment-router2 # 路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，通常配置服务名
          uri: lb://payment-service
          predicates:
            - Path=/provider/pay/gateway/selectOne/** #  断言，路径相匹配的进行路由