server:
  port: 8002
spring:
  application:
    name: consumer-openfeign-order-service
  cloud:
    consul:
      host: 127.0.0.1 # consul地址
      port: 8500      # consul端口 默认：8500
      discovery:
        prefer-ip-address: true  # 优先使用IP注册
        service-name: ${spring.application.name}
logging:
  level:
    com.at.cloud: debug