server:
  port: 8002
spring:
  application:
    name: consumer-openfeign-order-service
  cloud:
    consul:
#      host: 127.0.0.1 # consul地址
      host: 192.168.216.129  # consul地址
      port: 8500      # consul端口 默认：8500
      discovery:
        prefer-ip-address: true  # 优先使用IP注册
        service-name: ${spring.application.name}
# =========================openfeign=====================
    openfeign:
      client:
        config:
          default:
            connect-timeout: 4000 # 连接超时时间
            read-timeout: 4000  # 读取超时时间
          payment-service:
            connect-timeout: 5000   # 连接超时时间
            read-timeout: 5000   # 读取超时时间
      #            retryer: com.at.cloud  # 重试
      httpclient:
        hc5:
          enabled: true # HttpClient5 配置开启
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json  # 压缩媒体类型
          min-request-size: 2048  # 最小请求阈值长度
        response:
          enabled: true
# =====================logging=====================
logging:
  level:
    com.atguigu.cloud.apis.PayFeignApis: debug  # 记录器的名称是用于创建 Feign 客户端的接口的完整类名
# ====================zipkin=====================
management:
  zipkin:
    tracing:
      endpoint: http://192.168.216.129:9411/api/v2/spans  # 默认是localhost:9411
  tracing:
    sampling:
      probability: 1.0 #采样率默认为0.1(0.1就是10次只能有一次被记录下来)，值越大收集越及时。采用范围：0.0 - 1.0